legocollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('lego/', views.lego_index, name='index'),
  path('lego/<int:lego_id>/', views.lego_detail, name='detail'),
  path('lego/create/', views.LegoCreate.as_view(), name='lego_create'),
  path('lego/<int:pk>/update/', views.LegoUpdate.as_view(), name='lego_update'),
  path('lego/<int:pk>/delete/', views.LegoDelete.as_view(), name='lego_delete'),
  path('lego/<int:lego_id>/add_building/', views.add_building, name='add_building'),
  path('lego/<int:lego_id>/assoc_builder/<int:builder_id>/', views.assoc_builder, name='assoc_builder'),
  path('lego/<int:lego_id>/unassoc_builder/<int:builder_id>/', views.unassoc_builder, name='unassoc_builder'),
  path('builders/', views.BuilderList.as_view(), name='builders_index'),
  path('builders/<int:pk>/', views.BuilderDetail.as_view(), name='builders_detail'),
  path('builders/create/', views.BuilderCreate.as_view(), name='builders_create'),
  path('builders/<int:pk>/update/', views.BuilderUpdate.as_view(), name='builders_update'),
  path('builders/<int:pk>/delete/', views.BuilderDelete.as_view(), name='builders_delete'),
]

main_app/models.py
from email.policy import default
from django.db import models
from django.urls import reverse
from datetime import date

# Create your models here.

FUN_RATING = (
  ('1','Not Fun'),
  ('2','Kinda Fun'),
  ('3','Very Fun'),
)

class Builder(models.Model):
  name = models.CharField(max_length=50)
  build_date = models.DateField()

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('builders_detail', kwargs={'pk': self.id})


class Lego(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  pieces = models.IntegerField()
  cost = models.IntegerField()
  store_page = models.CharField(max_length=200)
  set_id = models.IntegerField()
  owned = models.BooleanField(default=False)
  
  builders = models.ManyToManyField(Builder)

  def __str__(self):
    return f'{self.name} ({self.id})'

  def get_absolute_url(self):
    return reverse('detail', kwargs={'lego_id': self.id})


class Building(models.Model):
  date = models.DateField('Building Date')
  rating = models.CharField(
    max_length=1,
    choices=FUN_RATING,
    default=FUN_RATING[1][0]
  )
  lego = models.ForeignKey(
    Lego,
    on_delete=models.CASCADE
  )

  def __str__(self):
    return f'{self.get_rating_display()} on {self.date}'

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Building

class BuildingForm(ModelForm):
  class Meta:
    model = Building
    fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Lego, Builder
from .forms import BuildingForm

# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def lego_index(request):
  lego = Lego.objects.all()
  return render(request, 'lego/index.html', {
    'lego': lego
  })

def lego_detail(request, lego_id):
  lego = Lego.objects.get(id=lego_id)
  id_list = lego.builders.all().values_list('id')
  builders_lego_doesnt_have = Builder.objects.exclude(id__in=id_list)
  building_form = BuildingForm()
  return render(
    request,
    'lego/detail.html',
    {
      'lego': lego,
      'building_form': building_form,
      'lego': builders_lego_doesnt_have
    }
  )

class LegoCreate(CreateView):
  model = Lego
  fields = ['name', 'description', 'pieces', 'cost', 'store_page', 'set_id']

class LegoUpdate(UpdateView):
  model = Lego
  fields = ['name', 'description', 'pieces', 'cost', 'store_page', 'set_id']

class LegoDelete(DeleteView):
  model = Lego
  success_url = '/lego/'

def add_building(request, lego_id):
  form = BuildingForm(request.POST)
  
  if form.is_valid():
    new_building = form.save(commit=False)
    new_building.lego_id = lego_id
    new_building.save()
  
  return redirect('detail', lego_id=lego_id)

def assoc_builder(request, lego_id, builder_id):
  lego = Lego.objects.get(id=lego_id)
  lego.builders.add(builder_id)
  return redirect('detail', lego_id=lego_id)

def unassoc_builder(request, lego_id, builder_id):
  Lego.objects.get(id=lego_id).builders.remove(builder_id)
  return redirect('detail', lego_id=lego_id)

class BuilderList(ListView):
  model = Builder

class BuilderDetail(DetailView):
  model = Builder

class BuilderCreate(CreateView):
  model = Builder
  fields = ['date', 'rating']

class BuilderUpdate(UpdateView):
  model = Builder
  fields = ['date', 'rating']

class BuilderDelete(DeleteView):
  model = Builder
  success_url = '/builders/'

main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Lego Collector</title>
</head>
<body>
    <h1>About the Lego Collector</h1>
    <hr>
    <p>Hire the Lego Collector!</p>
    <footer>All Rights Reserved, &copy; 2022 Lego Collector</footer>
</body>
</html>

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lego Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Lego Collector</a></li>
                </ul>
                <ul class="right">
                  <li><a href="{% url 'about' %}">About</a></li>
                  <li><a href="{% url 'lego_create' %}">Add a Lego Set</a></li>
                  <li><a href="{% url 'index' %}">View All My Lego</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="page-footer">
       <div class="right">All Rights Reserved, &copy; 2022 Lego Collector &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/lego/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Lego Collector</h1>
<hr>
<p>Learn more about the Lego Collector!</p>

{% endblock %}

main_app/templates/lego/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Lego Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ lego.title }}</span>
        <p>Description: {{ lego.description|linebreaks }}</p>
        <p>Pieces: {{ lego.pieces }}</p>
        {% if lego.cost > 0 %}
          <p>Cost: {{ lego.cost }}</p>
        {% else %}
          <p>Cost: Free</p>
        {% endif %}
        <p>Store Page: <a href="{{ lego.store_page }}">Link</a></p>
        <p>Set ID: {{ lego.set_id }}</p>
        {% if lego.owned == True %}
          <p>Owned: Yes</p>
        {% else %}
          <p>Owned: No</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'lego_update' lego.id %}">Edit</a>
        <a href="{% url 'lego_delete' lego.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_building' lego.id %}" method="POST">
      {% csrf_token %}
      {{ building_form.as_p }}
      <button class="btn" type="submit">Add Building</button>
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for building in lego.building_set.all %}
        <tr>
          <td>{{building.date}}</td>
          <td>{{building.get_description_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

main_app/templates/lego/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/lego/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Lego List</h1>

{% for lego_set in lego %}
    <div class="card">
        <a href="{% url 'detail' lego_set.id %}">
            <div class="card-content">
                <span class="card-title">{{ lego_set.title }}</span>
                <p>Description: {{ lego_set.description|linebreaks }}</p>
                <p>Pieces: {{ lego_set.pieces }}</p>
                {% if lego_set.cost > 0 %}
                    <p>Cost: {{ lego_set.cost }}</p>
                {% else %}
                    <p>Cost: Free</p>
                {% endif %}
                <p>Store Page: {{ lego_set.store_page }}</p>
                <p>Set ID: {{ lego_set.set_id }}</p>
                {% if lego_set.owned == True %}
                    <p>Owned: Yes</p>
                {% else %}
                    <p>Owned: No</p>
                {% endif %}
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/builder_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Builder</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'builders_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/builder_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Builder Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ builder.name }}</span>
        <p>Date Built: {{ builder.date_built }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'builders_update' builder.id %}">Edit</a>
        <a href="{% url 'builders_delete' builder.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/builder_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Builder</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/builder_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'builders_detail' builder.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ builder.name }}</span>
            <p>Date Built: {{ builder.date_built }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/confirm_delete_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Lego Set</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' lego.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/lego_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
  {% else %}
    <h1>Add Lego Set</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}